# This is a basic workflow to help you get started with Actions

name: Doxygen Action

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
  push:
    branches: [ main ]
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set version
        shell: bash
        run: |
          GRSISORT_VERSION="$(git describe --abbrev=0 --tags)"
          echo "DOXYGEN_GRSISORT_VERSION=\"$GRSISORT_VERSION\"" >> "$GITHUB_ENV"

    # Check out the data libraries
      - name: Checkout GRSIData
        uses: actions/checkout@v5
        with:
          repository: GRIFFINCollaboration/GRSIData
          path: GRSIData

      - name: Checkout ILLData
        uses: actions/checkout@v5
        with:
          repository: UoG-Nuclear-Physics-Group/ILLData
          path: IllData

      - name: Checkout iThembaData
        uses: actions/checkout@v5
        with:
          repository: UoG-Nuclear-Physics-Group/iThembaData
          path: iThembaData

      - name: Checkout HILData
        uses: actions/checkout@v5
        with:
          repository: UoG-Nuclear-Physics-Group/HILData
          path: HILData

      - name: Create footer
        shell: bash
        run: |
          doxygen/makehtmlfooter.sh > doxygen/footer.html

      - name: Doxygen Action
        uses: mattnotmitt/doxygen-action@v1.12.0
        with:
          # Path to Doxyfile
          doxyfile-path: "Doxyfile" # default is ./Doxyfile
            # Working directory
          working-directory: "doxygen/" # default is .
            #enable-latex: true # default is false

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
            # Default Doxyfile build documentation to html directory. 
            # Change the directory if changes in Doxyfile
          publish_dir: doxygen/html
            # this corresponds to: http://griffincollaboration.github.io/grsisort/index.html
            # old: https://rawgit.com/wiki/GriffinCollaboration/GRSISort/technical-docs/ROOT-Gen-Html/htmldoc/index.html
